use env, run tests
Signed-off-by: jkalinic <jkalinic@redhat.com>

diff --git a/.github/workflows/pre-release.yml b/.github/workflows/pre-release.yml
--- a/.github/workflows/pre-release.yml
+++ b/.github/workflows/pre-release.yml
@@ -16,19 +16,20 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: Ensure upgrade YAMLs changed
+      - name: Ensure old operator version was bumped
         run: |
-          CHANGED=$(git diff --name-only \
+          CHANGED=$(git diff \
             ${{ github.event.pull_request.base.sha }} \
             ${{ github.event.pull_request.head.sha }} \
-            | grep -E "systemtests/src/test/resources/upgrade/(YamlUpgrade.yaml)" || true)
+            -- systemtests/src/main/java/com/github/streamshub/systemtests/Environment.java \
+            | grep -E "^[+-].*OLD_CONSOLE_OPERATOR_VERSION" || true)
 
           if [ -z "$CHANGED" ]; then
-            echo "❌[ERROR]: YamlUpgrade.yaml was not modified in this PR, exiting the flow."
+            echo "❌[ERROR]: OLD_CONSOLE_OPERATOR_VERSION in Environment.java was not modified in this PR, exiting the flow."
             exit 1
           fi
 
-          echo "✔️ Upgrade YAML change detected: $CHANGED"
+          echo "✔️ OLD_CONSOLE_OPERATOR_VERSION change detected: $CHANGED"
 
       - name: Retrieve Project Metadata
         uses: smallrye/project-metadata-action@62527b4a896343d4c0c6b2a61eff07f6b59fcbd8
